"""
Django settings for disasterapp project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z59pa5i1fls*agca__kkgf_k7o!w*i&lni=257b59t1p1udw$4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['disasterproject-env.eba-vugwmymq.us-east-1.elasticbeanstalk.com',
    '127.0.0.1',
    'localhost',
    '172.31.39.217',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'feed',
    "storages", 

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'disasterapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'disasterapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'demo_1',
        'USER': 'disasterconnect',
        'PASSWORD': '03085294157a',
        'HOST': 'database-1.ceafuwdtezh0.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# IMAGE_UPLOAD_PATH = os.path.join(BASE_DIR, 'static', 'images')

# PayPal Configuration
PAYPAL_MODE = 'sandbox'  # Change to 'live' for production
PAYPAL_CLIENT_ID = 'AST-B84zzNsWmz1_ddX3ax8KphTDEvYu8Oj0xIaYdp9VgSgeEGZMFNmKhULWU5BfbdEL1yzvh93CK4jw'
PAYPAL_CLIENT_SECRET = 'EKjBzBkH7zMot739ANOLLKK9CjI2uRT7HyCIWvK-ItYhIvLD2YQdJ3iImcpz-M68QoudV6LxeiWMa0iD'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = [os.path.join(BASE_DIR, 'media')]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'habibchoudary855@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'ersp eobq putn xuvy'  # Use an App Password, not your actual password

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AWS_STORAGE_BUCKET_NAME = "your-receipt-bucket"
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
# AWS_S3_CUSTOM_DOMAIN = f"https://disasterconnect-images.s3.amazonaws.com"
AWS_DYNAMODB_TABLES = {
    'DisasterPosts': 'DisasterPosts',
    'Donations': 'Donations'
}
AWS_SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:592027060252:DisasterAlerts"
# AWS_STORAGE_BUCKET_NAME = "disasterconnect-images"

AWS_ACCESS_KEY_ID = "ASIAYTV4QBAOHANJ5P6O"
AWS_SECRET_ACCESS_KEY = "a0Iej6e+M/gWwKGG1D/3h2bjMoqPaDUfvz5pkl/v"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEOz//////////wEaCXVzLXdlc3QtMiJIMEYCIQDPaQ5eT4hcd4g4rGFEKn+TRJfy7ZHd83gY17vrO5k2fQIhAIrlpyf5LC7H6XkU9EM9SwRuqEIkcI3bBhZtaU8hJ62oKrQCCFUQARoMNTkyMDI3MDYwMjUyIgyJd73g8YVtKL7y0msqkQJj6DtASj33A8Etp27qpMD0dqFZLUcRIJxmcTTGFq97yAa5qjnUT2D/1/XS5FcwdKQUj5LGYilGZiRHsSGZvgW1p8zUnSfle/LWRBQEJe2lI2kk50oprzpnTOqXwUhOtUb1E9hRfJz6C6VaAzxVrdagERpmfsJGq7iHf3gcT/UfH9t5+ulnMLEgTsa0IZppfrJ9u4bZ7AF0UFfgY64z8Dm+xse9nKopDtl7P+YEs1jCdCkQ+DT+FjmWvC0uuqqXLLEDQP/f3sL62+wZsYcS2PA6P/LjM/GbjXHGpw6/+tbLnB4nx3zRelyN7WO5snaDGsoTA0lrhqpJyXg5zdKwgtGdjPq5xnnKpY67CO25woYWtI4w472YvwY6nAH2tJqieUU6gcluakQafHsPFc2K80sGzinvgJtnQN8s4fGaOxW7nnKqwAij2H3/LqOphrzmrusvZgNnGYiYZPsmRFVmGffXCR9zCalNFs1c6jWWe1zXPg61ne86XyRwJbRFsTjm/lD1Std87NHcyQTGiPIHVMN6CT/xdSd4Dr/gO9L4ymwjq3+qbYwefaViJc0wHwXIIb8p3k7yCKo="

AWS_REGION_NAME = "us-east-1"

