# Generated by Django 5.1.6 on 2025-03-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_disasterpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
